/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-01-08 09:31:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tset01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("function go_sec() {\r\n");
      out.write("var s1 = document.all.s1;\r\n");
      out.write("var s2 = document.all.s2;\r\n");
      out.write("var s3 = document.all.s3;\r\n");
      out.write("if(s1.value == \"분식류\") {\r\n");
      out.write("  s2.style.display=\"\";\r\n");
      out.write("  s3.style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("else if(s1.value == \"식사류\") {\r\n");
      out.write("  s2.style.display=\"none\";\r\n");
      out.write("  s3.style.display=\"\";\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function go_submit() {\r\n");
      out.write("var s1 = document.all.s1;\r\n");
      out.write("if(s1.value == \"\") {\r\n");
      out.write("  alert(\"분식으로 할건지 식사로 할건지 먼저 선택하세요!\");\r\n");
      out.write("  s1.focus();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var s2 = document.all.s2;\r\n");
      out.write("var s3 = document.all.s3;\r\n");
      out.write("var newwin;\r\n");
      out.write("\r\n");
      out.write("  if(s1.value == \"분식류\") {\r\n");
      out.write("   if(s2.value == \"\") {\r\n");
      out.write("    alert(\"어떤 음식을 드실래용?\");\r\n");
      out.write("    s2.focus();\r\n");
      out.write("   } else {\r\n");
      out.write("    newwin = window.open(\"about:blank\", \"\", \"\");\r\n");
      out.write("    newwin.document.write(s2.value + \"맛있게 드세용\");\r\n");
      out.write("   }\r\n");
      out.write("  }\r\n");
      out.write("  else if(s1.value == \"식사류\") {\r\n");
      out.write("   if(s3.value == \"\") {\r\n");
      out.write("    alert(\"어떤 음식을 드실래용?\");\r\n");
      out.write("    s3.focus();\r\n");
      out.write("   } else {\r\n");
      out.write("    newwin = window.open(\"about:blank\", \"\", \"\");\r\n");
      out.write("    newwin.document.write(s3.value + \"맛있게 드세용\");\r\n");
      out.write("   }\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<select name=\"s1\" onchange=\"go_sec()\">\r\n");
      out.write("<option value=\"\">==선택하세요==</option>\r\n");
      out.write("<option value=\"분식류\">분식류</option>\r\n");
      out.write("<option value=\"식사류\">식사류</option>\r\n");
      out.write("</select>\r\n");
      out.write("<select name=\"s2\" style=\"display:none\">\r\n");
      out.write("<option value=\"\">분식골라</option>\r\n");
      out.write("<option value=\"만두\">만두</option>\r\n");
      out.write("<option value=\"떡볶이\">떡볶이</option>\r\n");
      out.write("<option value=\"김밥\">김밥</option>\r\n");
      out.write("</select>\r\n");
      out.write("<select name=\"s3\" style=\"display:none\">\r\n");
      out.write("<option value=\"\">식사골라</option>\r\n");
      out.write("<option value=\"비빔밥\">비빔밥</option>\r\n");
      out.write("<option value=\"볶은밥\">볶은밥</option>\r\n");
      out.write("<option value=\"카레덮밥\">카레덮밥</option>\r\n");
      out.write("</select>\r\n");
      out.write("<input type=\"button\" value=\"주문\" onClick=\"go_submit()\">\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
