/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-01-09 11:21:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.indexform;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <!-- LEFT-CONTAINER -->\r\n");
      out.write("            <div class=\"left-container container\">\r\n");
      out.write("                <div class=\"menu-box block\"> <!-- MENU BOX (LEFT-CONTAINER) -->\r\n");
      out.write("                    <h2 class=\"titular\">나와라한글</h2>\r\n");
      out.write("                    <ul class=\"menu-box-menu\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"menu-box-tab\" href=\"#6\"><span class=\"icon fontawesome-envelope scnd-font-color\"></span>한글!<div class=\"menu-box-number\">24</div></a>                            \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"menu-box-tab\" href=\"#8\"><span class=\"icon entypo-paper-plane scnd-font-color\"></span>Invites<div class=\"menu-box-number\">3</div></a>                            \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"menu-box-tab\" href=\"#10\"><span class=\"icon entypo-calendar scnd-font-color\"></span>Events<div class=\"menu-box-number\">5</div></a>                            \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"menu-box-tab\" href=\"#12\"><span class=\"icon entypo-cog scnd-font-color\"></span>Account Settings</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"menu-box-tab\" href=\"#13\"><sapn class=\"icon entypo-chart-line scnd-font-color\"></sapn>Statistics</a>\r\n");
      out.write("                        </li>                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("             <!--    <div class=\"donut-chart-block block\">  DONUT CHART BLOCK (LEFT-CONTAINER) -->\r\n");
      out.write("                   <!--  <h2 class=\"titular\">OS AUDIENCE STATS</h2>\r\n");
      out.write("                    <div class=\"donut-chart\">\r\n");
      out.write("                        DONUT-CHART by @kseso http://codepen.io/Kseso/pen/phiyL\r\n");
      out.write("                        <div id=\"porcion1\" class=\"recorte\"><div class=\"quesito ios\" data-rel=\"21\"></div></div>\r\n");
      out.write("                        <div id=\"porcion2\" class=\"recorte\"><div class=\"quesito mac\" data-rel=\"39\"></div></div>\r\n");
      out.write("                        <div id=\"porcion3\" class=\"recorte\"><div class=\"quesito win\" data-rel=\"31\"></div></div>\r\n");
      out.write("                        <div id=\"porcionFin\" class=\"recorte\"><div class=\"quesito linux\" data-rel=\"9\"></div></div>\r\n");
      out.write("                        END DONUT-CHART by @kseso http://codepen.io/Kseso/pen/phiyL    \r\n");
      out.write("                        <p class=\"center-date\">JUNE<br><span class=\"scnd-font-color\">2013</span></p> \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"os-percentages horizontal-list\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p class=\"ios os scnd-font-color\">iOS</p>\r\n");
      out.write("                            <p class=\"os-percentage\">21<sup>%</sup></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p class=\"mac os scnd-font-color\">Mac</p>\r\n");
      out.write("                            <p class=\"os-percentage\">48<sup>%</sup></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p class=\"linux os scnd-font-color\">Linux</p>\r\n");
      out.write("                            <p class=\"os-percentage\">9<sup>%</sup></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p class=\"win os scnd-font-color\">Win</p>\r\n");
      out.write("                            <p class=\"os-percentage\">32<sup>%</sup></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"line-chart-block block clear\"> LINE CHART BLOCK (LEFT-CONTAINER)\r\n");
      out.write("                    <div class=\"line-chart\">\r\n");
      out.write("                      LINE-CHART by @kseso http://codepen.io/Kseso/pen/phiyL\r\n");
      out.write("                        <div class='grafico'>\r\n");
      out.write("                           <ul class='eje-y'>\r\n");
      out.write("                             <li data-ejeY='30'></li>\r\n");
      out.write("                             <li data-ejeY='20'></li>\r\n");
      out.write("                             <li data-ejeY='10'></li>\r\n");
      out.write("                             <li data-ejeY='0'></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                           <ul class='eje-x'>\r\n");
      out.write("                             <li>Apr</li>\r\n");
      out.write("                             <li>May</li>\r\n");
      out.write("                             <li>Jun</li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                             <span data-valor='25'>\r\n");
      out.write("                               <span data-valor='8'>\r\n");
      out.write("                                 <span data-valor='13'>\r\n");
      out.write("                                   <span data-valor='5'>   \r\n");
      out.write("                                     <span data-valor='23'>   \r\n");
      out.write("                                     <span data-valor='12'>\r\n");
      out.write("                                         <span data-valor='15'>\r\n");
      out.write("                                         </span></span></span></span></span></span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        END LINE-CHART by @kseso http://codepen.io/Kseso/pen/phiyL\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"time-lenght horizontal-list\">\r\n");
      out.write("                        <li><a class=\"time-lenght-btn\" href=\"#14\">Week</a></li>\r\n");
      out.write("                        <li><a class=\"time-lenght-btn\" href=\"#15\">Month</a></li>\r\n");
      out.write("                        <li><a class=\"time-lenght-btn\" href=\"#16\">Year</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"month-data clear\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p>APR<span class=\"scnd-font-color\"> 2013</span></p>\r\n");
      out.write("                            <p><span class=\"entypo-plus increment\"> </span>21<sup>%</sup></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p>MAY<span class=\"scnd-font-color\"> 2013</span></p>\r\n");
      out.write("                            <p><span class=\"entypo-plus increment\"> </span>48<sup>%</sup></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p>JUN<span class=\"scnd-font-color\"> 2013</span></p>\r\n");
      out.write("                            <p><span class=\"entypo-plus increment\"> </span>35<sup>%</sup></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"media block\"> MEDIA (LEFT-CONTAINER)\r\n");
      out.write("                    <div id=\"media-display\">\r\n");
      out.write("                        <a class=\"media-btn play\" href=\"#23\"><span class=\"fontawesome-play\"></span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"media-control-bar\">\r\n");
      out.write("                        <a class=\"media-btn play\" href=\"#23\"><span class=\"fontawesome-play scnd-font-color\"></span></a>\r\n");
      out.write("                        <p class=\"time-passed\">4:15 <span class=\"time-duration scnd-font-color\">/ 9:23</span></p>\r\n");
      out.write("                        <a class=\"media-btn volume\" href=\"#24\"><span class=\"fontawesome-volume-up scnd-font-color\"></span></a>\r\n");
      out.write("                        <a class=\"media-btn resize\" href=\"#25\"><span class=\"fontawesome-resize-full scnd-font-color\"></span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"social horizontal-list block\"> SOCIAL (LEFT-CONTAINER)\r\n");
      out.write("                    <li class=\"facebook\"><p class=\"icon\"><span class=\"zocial-facebook\"></span></p><p class=\"number\">248k</p></li>\r\n");
      out.write("                    <li class=\"twitter\"><p class=\"icon\"><span class=\"zocial-twitter\"></span></p><p class=\"number\">30k</p></li>\r\n");
      out.write("                    <li class=\"googleplus\"><p class=\"icon\"><span class=\"zocial-googleplus\"></span></p><p class=\"number\">124k</p></li>\r\n");
      out.write("                    <li class=\"mailbox\"><p class=\"icon\"><span class=\"fontawesome-envelope\"></span></p><p class=\"number\">89k</p></li>\r\n");
      out.write("                </ul> -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
