/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-01-07 11:00:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.indexform;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class middle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write(" \r\n");
      out.write("                 <!-- MIDDLE-CONTAINER -->\r\n");
      out.write("            <div class=\"middle-container container_m\">\r\n");
      out.write("                <div class=\"profile block\"> <!-- PROFILE (MIDDLE-CONTAINER) -->\r\n");
      out.write("                    <p>공지사항</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            <!--     <div class=\"weather block clear\"> WEATHER (MIDDLE-CONTAINER)\r\n");
      out.write("                    <h2 class=\"titular\"><span class=\"icon entypo-location\"></span><strong>CLUJ-NAPOCA</strong>/RO</h2>\r\n");
      out.write("                    <div class=\"current-day\">\r\n");
      out.write("                        <p class=\"current-day-date\">FRI 29/06</p>\r\n");
      out.write("                        <p class=\"current-day-temperature\">24º<span class=\"icon-cloudy\"></span></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"next-days\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#43\">\r\n");
      out.write("                                <p class=\"next-days-date\"><span class=\"day\">SAT</span> <span class=\"scnd-font-color\">29/06</span></p>\r\n");
      out.write("                                <p class=\"next-days-temperature\">25º<span class=\"icon icon-cloudy scnd-font-color\"></span></p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#44\">\r\n");
      out.write("                                <p class=\"next-days-date\"><span class=\"day\">SUN</span> <span class=\"scnd-font-color\">30/06</span></p>\r\n");
      out.write("                                <p class=\"next-days-temperature\">22º<span class=\"icon icon-cloudy2 scnd-font-color\"></span></p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#45\">\r\n");
      out.write("                                <p class=\"next-days-date\"><span class=\"day\">MON</span> <span class=\"scnd-font-color\">01/07</span></p>\r\n");
      out.write("                                <p class=\"next-days-temperature\">24º<span class=\"icon icon-cloudy2 scnd-font-color\"></span></p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#46\">\r\n");
      out.write("                                <p class=\"next-days-date\"><span class=\"day\">TUE</span> <span class=\"scnd-font-color\">02/07</span></p>\r\n");
      out.write("                                <p class=\"next-days-temperature\">26º<span class=\"icon icon-cloudy scnd-font-color\"></span></p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\">\r\n");
      out.write("                                <p class=\"next-days-date\"><span class=\"day\">WED</span> <span class=\"scnd-font-color\">03/07</span></p>\r\n");
      out.write("                                <p class=\"next-days-temperature\">27º<span class=\"icon icon-sun scnd-font-color\"></span></p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\">\r\n");
      out.write("                                <p class=\"next-days-date\"><span class=\"day\">THU</span> <span class=\"scnd-font-color\">04/07</span></p>\r\n");
      out.write("                                <p class=\"next-days-temperature\">29º<span class=\"icon icon-sun scnd-font-color\"></span></p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tweets block\"> TWEETS (MIDDLE-CONTAINER)\r\n");
      out.write("                    <h2 class=\"titular\"><span class=\"icon zocial-twitter\"></span>LATEST TWEETS</h2>\r\n");
      out.write("                    <div class=\"tweet first\">\r\n");
      out.write("                        <p>Ice-cream trucks only play music when out of ice-cream. Well played dad. On <a class=\"tweet-link\" href=\"#17\">@Quora</a></p>\r\n");
      out.write("                        <p><a class=\"time-ago scnd-font-color\" href=\"#18\">3 minutes ago</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tweet\">\r\n");
      out.write("                        <p>We are in the process of pushing out all of the new CC apps! We will tweet again once they are live <a class=\"tweet-link\" href=\"#19\">#CreativeCloud</a></p>\r\n");
      out.write("                        <p><a class=\"scnd-font-color\" href=\"#20\">6 hours ago</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> \r\n");
      out.write("                <ul class=\"social block\"> SOCIAL (MIDDLE-CONTAINER)\r\n");
      out.write("                    <li><a href=\"#50\"><div class=\"facebook icon\"><span class=\"zocial-facebook\"></span></div><h2 class=\"facebook titular\">SHARE TO FACEBOOK</h2></li></a>\r\n");
      out.write("                    <li><a href=\"#51\"><div class=\"twitter icon\"><span class=\"zocial-twitter\"></span></div><h2 class=\"twitter titular\">SHARE TO TWITTER</h2></li></a>\r\n");
      out.write("                    <li><a href=\"#52\"><div class=\"googleplus icon\"><span class=\"zocial-googleplus\"></span></div><h2 class=\"googleplus titular\">SHARE TO GOOGLE+</h2></li></a>\r\n");
      out.write("                </ul> -->\r\n");
      out.write("            </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
